name: VerbDrill
options:
  bundleIdPrefix: com.verbdrill
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_KEY_CFBundleDisplayName: "Verb Drill"

packages:
  Heartbeat:
    url: https://github.com/maierru/heartbeat-tracker.git
    from: 1.1.0

targets:
  VerbDrill:
    type: application
    platform: iOS
    sources:
      - VerbDrill
    dependencies:
      - package: Heartbeat
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cc.verb-drill.app
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "3"
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: VerbDrill/Info.plist
      properties:
        UIBackgroundModes:
          - fetch
        BGTaskSchedulerPermittedIdentifiers:
          - cc.verb-drill.heartbeat
